# fly.toml app configuration file generated for sapphic-moe on 2025-06-24T02:11:38+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sapphic'
primary_region = 'fra'

[build]

[http_service]
internal_port = 4321
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']
