# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Create env file
        run: |
          cat << 'EOF' > .env
          PUBLIC_TURNSTILE_SITE_KEY=${{ secrets.PUBLIC_TURNSTILE_SITE_KEY }}
          TURNSTILE_SECRET_TOKEN=${{ secrets.TURNSTILE_SECRET_TOKEN }}
          OWM_API_KEY=${{ secrets.OWM_API_KEY }}
          LASTFM_API_KEY=${{ secrets.LASTFM_API_KEY }}
          ASTRO_DB_REMOTE_URL=${{ secrets.ASTRO_DB_REMOTE_URL }}
          ASTRO_DB_APP_TOKEN=${{ secrets.ASTRO_DB_APP_TOKEN }}
          ASTRO_DB_GUESTBOOK_DASHBOARD_URL=${{ secrets.ASTRO_DB_GUESTBOOK_DASHBOARD_URL }}
          DISCORD_CONTACT_WEBHOOK_URL=${{ secrets.DISCORD_CONTACT_WEBHOOK_URL }}
          DISCORD_GUESTBOOK_WEBHOOK_URL=${{ secrets.DISCORD_GUESTBOOK_WEBHOOK_URL }}
          DISCORD_USER_ID=${{ secrets.DISCORD_USER_ID }}
          LANYARD_API_URL=${{ secrets.LANYARD_API_URL }}
          EOF

      - name: Deploy to Fly.io
        run: |
          ENV_CONTENT=$(cat .env)
          flyctl deploy --remote-only \
            --build-arg COMMIT_HASH=$(git rev-parse --short HEAD) \
            --build-arg COMMIT_DATE="$(git log -1 --format=%cd --date=iso)" \
            --build-arg ENV_FILE="$ENV_CONTENT"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
